# Generated by Django 3.0.7 on 2020-06-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200618_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_pic',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
